# Generated by Django 4.1.2 on 2022-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalsOdors',
            fields=[
                ('idChemicals', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=450)),
                ('IUPAC_name', models.CharField(max_length=450)),
                ('SMILE', models.CharField(max_length=450, unique=True)),
                ('Pubchem_CID', models.CharField(max_length=450)),
                ('Mixture', models.SmallIntegerField()),
                ('Synonyms', models.CharField(max_length=450)),
                ('CAS', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Chemicals',
            },
        ),
        migrations.CreateModel(
            name='OlfactoryReceptors',
            fields=[
                ('idOlfactoryReceptors', models.IntegerField(primary_key=True, serialize=False)),
                ('GeneName', models.CharField(max_length=45)),
                ('idUniprot', models.CharField(max_length=45)),
                ('Synonym', models.CharField(max_length=45)),
                ('Species', models.CharField(max_length=45)),
                ('Sequence', models.CharField(max_length=5000)),
                ('URL_3D_Structure', models.CharField(max_length=45)),
                ('FileName_3D_Structure', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'OlfactoryReceptors',
            },
        ),
        migrations.CreateModel(
            name='Smell_Percepts',
            fields=[
                ('idSmell_Percepts', models.IntegerField(primary_key=True, serialize=False)),
                ('Odor', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Smell_Percepts',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
