# Generated by Django 3.2.16 on 2023-06-05 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odor', '0002_alter_chemicalsodors_smile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalsodors',
            name='InChi',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalsodors',
            name='InChi_Key',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalsodors',
            name='Molecular_Formula',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalsodors',
            name='Molecular_Weight',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalsodors',
            name='Synonyms',
            field=models.CharField(max_length=800),
        ),
    ]
