# Generated by Django 4.2.10 on 2024-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odor', '0003_auto_20230605_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
